---
name: 'CI'

on:
  push:
    branches: ['trunk']
    paths-ignore:
      - '.editorconfig'
      - '.gitignore'
      - '.golangci.toml'
      - '.builds/'
      - '.tmp/'
      - 'LICENSE.md'
      - 'README.md'
  pull_request:
    branches: ['trunk']
    paths-ignore:
      - '.editorconfig'
      - '.gitignore'
      - '.golangci.toml'
      - '.builds/'
      - '.tmp/'
      - 'LICENSE.md'
      - 'README.md'

jobs:
  test:
    runs-on: 'ubuntu-latest'
    name: 'Tests'
    steps:
      - uses: 'actions/checkout@v3'

      - name: 'Setup Go environment'
        uses: 'actions/setup-go@v3'
        with:
          go-version: '>=1.20'
          cache: true

      - name: 'Run tests'
        run: 'make test'
