---
name: 'Lint'
on:
  push:
    paths-ignore:
      - '.editorconfig'
      - '.gitignore'
      - '.golangci.toml'
      - '.builds/'
      - '.tmp/'
      - 'LICENSE.md'
      - 'README.md'
  pull_request:
    paths-ignore:
      - '.editorconfig'
      - '.gitignore'
      - '.golangci.toml'
      - '.builds/'
      - '.tmp/'
      - 'LICENSE.md'
      - 'README.md'

permissions:
  contents: 'read'

jobs:
  go:
    name: 'Lint Go files'
    runs-on: 'ubuntu-latest'
    steps:
      - uses: 'actions/checkout@v3'

      - name: 'Setup Go environment'
        uses: 'actions/setup-go@v3'
        with:
          go-version: '>=1.20'
          cache: true

      - name: 'Download project dependencies'
        run: 'make init'

      - name: 'Run govulncheck'
        run: 'make vulnerabilities'

      - name: 'Run golangci-lint'
        run: 'make lint'
